### ISSUE TITLE
redundancy in element registration?

### ISSUE THREAD

**Issue by Nitin-Prabhakar** [webcomponents/custom-elements#10]
So, I am grasping the v1 specs for custom elements.Something that confuses me, is the element registration

```js
window.customElements.define('my-div', MyDiv, {extends: 'div'});
```
Now, if the custom element extends the HTMLDivElement,

`class myDiv extends HTMLDivElement{}`

Isnt it counter intuitive that I should specify the extends attribute as a third paramaeter?

I know it helps in identifying which element it extends, specifically, but the grammar

`class myDiv extends HTMLDivElement{}` itself, is pretty specific isn't it?

it is like we have the word regardless, but we need a new word irregardless , regardless of the fact that it does nothing but mean the same as regardless!

**Comment by ebidel** [comment]
From https://developers.google.com/web/fundamentals/primers/customelements/?hl=en#extend

> Notice that the call to `define()` changes slightly when extending a native element. The required third parameter tells the browser which tag you’re extending. This is necessary because many HTML tags share the same DOM interface. `<section>`, `<address>`, and `<em>` (among others) all share `HTMLElement`; both `<q>` and `<blockquote>` share `HTMLQuoteElement`; etc.. Specifying `{extends: 'blockquote'}` lets the browser know you’re creating a souped-up `<blockquote>` instead of a <q>. See the HTML spec for the full list of HTML’s DOM interfaces.
