### ISSUE TITLE
native-shim cannot be bundled because includes errors

### ISSUE THREAD

**Issue by Hotell** [webcomponents/custom-elements#100]
This is occurring when building app via webpack and uglify 

`Unexpected token: name (browserConstruction) [../~/source-map-loader!../~/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js:89,0]`

https://travis-ci.org/Hotell/skate-starter/builds/236986916#L306

any ideas?

**Comment by whyboris** [comment]
Exact same problem on our setup. The app works fine locally, but when the server tries to build, in its last step:
```
ERROR in polyfills.f73c9a87ee1979c6555e.bundle.js from UglifyJs
Unexpected token: punc ()) [polyfills.f73c9a87ee1979c6555e.bundle.js:1633,2]
```
Any ideas? Do we need to turn off `UglifyJs`?

**Comment by whyboris** [comment]
Issue resolved on the Angular CLI issue page: https://github.com/angular/angular-cli/issues/7509
The solution was to bypass uglification by including the script into the `angular-cli.json` file instead of the `polyfils.ts file`.

**Comment by bicknellr** [comment]
Hi, @whyboris, was this specifically an angular-cli issue? Anything on our end that still needs attention?

**Comment by whyboris** [comment]
In my case it was just an _angular-cli_ issue and no work is needed from _custom-elements_, thank you.
I hope my link to the angular issue will help others who end up running into the same problem 👍

**Comment by bicknellr** [comment]
Thanks, glad you figured it out! I'll close this bug then.
