### ISSUE TITLE
TypeError calling Object.setPrototypeOf in older browsers

### ISSUE THREAD

**Issue by javan** [webcomponents/custom-elements#105]
`Object.setPrototypeOf` is unsupported in Safari < 9, IE < 11, and some older mobile browsers ([full list](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf#Browser_compatibility)) so calling it, [as this library does](https://github.com/webcomponents/custom-elements/search?utf8=%E2%9C%93&q=setPrototypeOf&type=), throws an error and fails to upgrade the element.

Example: https://jsfiddle.net/javan/fzynsLn7/

<img width="1198" alt="screen shot 2017-06-25 at 2 33 44 pm" src="https://user-images.githubusercontent.com/5355/27518716-32ff7dcc-59b4-11e7-88ae-467896dd660b.png">

See the example's `setPrototype` helper function for a potential fix.

**Comment by bicknellr** [comment]
Hi @javan, Safari 8, IE 10, and earlier are outside our support range: https://github.com/webcomponents/webcomponentsjs#browser-support . This repo should probably link there from the local README; I'm pretty sure other people have run into weird issues with Safari 8 / IE 10. Also, changing the prototype chain of an element is also more generally part of the upgrade process.
