### ISSUE TITLE
Can we remove the console.warn()

### ISSUE THREAD

**Issue by dgt41** [webcomponents/custom-elements#106]
If you use this polyfill as standalone (e.g. not using the whole webcomponentsjs pack) there is always a message in the console:
https://github.com/webcomponents/custom-elements/blob/master/src/Patch/Element.js#L26

Will it be possible to remove this warning, at least for production code?

**Comment by bicknellr** [comment]
Yeah, I agree, this warning isn't necessary. If the browser you're running on doesn't support Shadow DOM (or doesn't have it polyfilled), it's not a problem that the custom elements polyfill really needs to worry about.
