### ISSUE TITLE
Can't define custom element in IE11 - "custom element constructors must be functions" error

### ISSUE THREAD

**Issue by lexigren** [webcomponents/custom-elements#109]
Looks like IE doesn't recognize my custom component as function (even while outputting it in console as [object function]) and returning false for instanceof Function.
I was trying to wrap component in function that will return newly created component, but got same error as soon as set my component's prototype for it. 

```
                function constr() {
                     return Reflect.construct(component, []);
                 }
                Object.setPrototypeOf(constr, component);
                Object.setPrototypeOf(constr.prototype, component.prototype);
                customElements.define(component.tagName, constr);
```

Did someone met this problem and found any possible solution?

**Comment by bicknellr** [comment]
IE11 doesn't have support for `Reflect`; are you doing some type of transpilation step? Any other info?

**Comment by snuggs** [comment]
@lexigren #ping

**Comment by SerkanSipahi** [comment]
Safari´s and IE´s native Element-Class it not a function. You have to map them to a function otherwise it throw an error.
```js
if (typeof HTMLElement === 'object'){
     let _Element = function(){};
     _Element.prototype = HTMLElement.prototype;
     HTMLElement = _Element;
}
```

**Comment by ananddc1989** [comment]
Any solution related to this issue ??
