### ISSUE TITLE
`Element#attachShadow` was not patched. redux

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/custom-elements#113]
I'd like the option to run cleanly on IE11 using only Custom Elements, HTML Import, and Template.  So...no shadow DOM or Shady DOM polyfill.  Everything looks good, with the exception of this one warning in `PatchElement`:

```
var PatchElement = function (internals) {
  if (Native.Element_attachShadow) {
    setPropertyUnchecked(Element.prototype, 'attachShadow', function (init) {
      var shadowRoot = Native.Element_attachShadow.call(this, init);
      this.__CE_shadowRoot = shadowRoot;
      return shadowRoot;
    });
  } else {
    console.warn('Custom Elements: `Element#attachShadow` was not patched.');
  }
```

It would be nice to have some option to suppress this warning.

**Comment by bicknellr** [comment]
This should be fixed as of tag [`v1.0.4`](https://github.com/webcomponents/custom-elements/blob/v1.0.4/src/Patch/Element.js#L13).
