### ISSUE TITLE
custom-elements seems to assume that html-imports adds .import to links before it actually does

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/custom-elements#114]
At load time, `var customElements = new CustomElementRegistry(internals);` is called which calls `this._documentConstructionObserver = new DocumentConstructionObserver(internals, document);` which in turn calls `this._internals.patchAndUpgradeTree(this._document);` which walks the tree and ends up calling `gatherElements()`.

But `gatherElements()`  has code including:

```
      var gatherElements = function gatherElements(element) {
        if (element.localName === 'link' && element.getAttribute('rel') === 'import') {
          var importNode = element.import;
```

**However**, if relying on the `html-imports` polyfill, the function `flatten()` in that module only runs once a given import has loaded.   And, apparently, it is `flatten()` that is responsible for adding the `import` property to a `link` element.  Yet `custom-elements` seems to be assuming that the `.import` property is available on a `link` element earlier.  It isn't.

Another way of saying this is that it seems that `custom-elements` is maybe mostly tested on Chrome where HTMLImports is native.  For testing `custom-elements` with the `html-imports` polyfill, it might make sense on Chrome to execute `delete HTMLLinkElement.prototype.import;` at the top of the test to make sure `custom-elements` works well with polyfilled HTMLImports.  `html-imports` looks for `import` to set its `useNative` flag.  Forcing use of the `html-imports` polyfill  would better emulate IE/Edge.

**Comment by TimvdLippe** [comment]
I think this is fixed in the latest version of the polyfill, where we wait for the load event if necessary: https://github.com/webcomponents/custom-elements/blob/6374f375f35d05aae344ee3b61f1f7a4c0be2a81/src/CustomElementInternals.js#L181-L218 Therefore, I am closing this issue.
