### ISSUE TITLE
Safari "TypeError: HTMLElementConstructor is not a constructor (evaluating 'super()')"

### ISSUE THREAD

**Issue by o-t-w** [webcomponents/custom-elements#118]
The polyfill is working for me in Firefox, but not in Safari. I am not using any of the other web components specs, just custom elements. 
I am getting the error message `TypeError: HTMLElementConstructor is not a constructor (evaluating 'super()')` in the console in Safari 9.1 (the last version of Safari before a native implementation of the spec)

An alternative polyfill is working as expected... 
https://github.com/WebReflection/document-register-element

**Comment by aaronshaf** [comment]
Same

**Comment by TimvdLippe** [comment]
We verify on Travis that our build works on Safari 9: https://github.com/webcomponents/custom-elements/blob/4d85c210b7207db7a22c172bc72d44117b0385ce/.travis.yml#L18 Could you provide a reproduction case that shows what is going wrong?

The error seems related to transpiling to ES5. Make sure that you are correctly loading the polyfills with ES5 support and use the ES5-adapter if necessary.
