### ISSUE TITLE
Using this in Edge

### ISSUE THREAD

**Issue by trusktr** [webcomponents/custom-elements#119]
I'd like to use this in Edge 13+ (supports native class syntax).

Does this require native-shim?

**Comment by trusktr** [comment]
Hmmm, I guess not. I get an error like the following in both Chrome and Edge:

```
Class constructor cannot be invoked without 'new'
```

Stack trace is like

```
Uncaught TypeError: Class constructor _Node cannot be invoked without 'new'
    at HTMLElement.StandInElement (i.js:16670)
    at CustomElementRegistry.define (i.js:16684)
    at Function.define (i.js:16094)
    at Object.useDefaultNames (i.js:16702)
    at VM682 pen.js:1
```

Here's a reproduction: https://codepen.io/anon/pen/dVJyNZ

**Comment by trusktr** [comment]
Oh, oops, I forgot that I _need_ to transpile `class`es then use the shim.

I tried that, but I can't seem to get it right. I've got an HTML file like this:

```html
<script src="./global.js"></script>

<script>
    infamous.html.useDefaultNames()
</script>

<style>
    i-node {
        border: 1px solid red;
    }
</style>

<i-scene>
    <i-node rotation="30 30 30">
    </i-node>
</script>
```

The file where `useDefaultNames()` is defined looks like this:

```js
// ...
import '@webcomponents/custom-elements'
import '@webcomponents/custom-elements/src/native-shim'
function useDefaultNames() {
    if (!customElements.get('i-node')) Node.define()
    if (!customElements.get('i-scene')) Scene.define()
}

export {
    // ...
    useDefaultNames,
}
```

where the `define()` calls the elements after importing native-shim.

I'm telling rollup-plugin-buble to _not_ transpile native-shim.js.

The transpilation results in `global.js` which contains all ES5 classes except for the one in `native-shim.js`.

Yet I still get this in Chrome:

```
Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
```

Any ideas?

**Comment by bicknellr** [comment]
>```js
>import '@webcomponents/custom-elements'
>import '@webcomponents/custom-elements/src/native-shim'
>```

I think you need to run the native shim before the polyfill: https://github.com/webcomponents/webcomponentsjs#custom-elements-es5-adapterjs.

**Comment by TimvdLippe** [comment]
@trusktr https://codepen.io/anon/pen/dVJyNZ is now working on my machine with Microsoft Edge 41.16299.15.0 and Microsoft EdgeHTML 16.16299. Is Edge 13 a strict requirement or did you mean supporting Edge in general? Because Edge support in general (on 16 etc..) should be working just fine now.

**Comment by trusktr** [comment]
How's the release cycle for Edge? With Chrome usually people have the latest Chrome, and the release cycle is fast. With Safari, it is slow, released with OS updates. If Edge is fast, I may not have to worry about it. IE was fairly slow, so I'll have to worry about earlier versions of Edge if it is also slow.

**Comment by TimvdLippe** [comment]
Per https://nl.wikipedia.org/wiki/Microsoft_Edge Edge 13 is almost 3 years old  now. It seems they release roughly every 6-10 months.

**Comment by trusktr** [comment]
But I mean, how is Edge update process? Do they auto-instancing the browser like Chrome? Because if not, then Edge 13 is probably still relevant just like previous versions of IE remained relevant for too long.

Chrome, in contrast, keeps itself updated automatically all the time with many users not even aware of updates. This is beneficial to making sure that saying something like "it works in Chrome" is actually meaningful because it is highly likely to be true, and it doesn't require "it works in Chrome 57 or earlier at the moment" which is something that Chrome's release strategy prevents.

That's what I mean. How is Edge. Is it like Chrome, or is it like IE in this regard?

**Comment by AndreasGalster** [comment]
Edge always updates with the latest Windows build, which is usually every 6-10 months as mentioned.

**Comment by TimvdLippe** [comment]
Per https://github.com/webcomponents/webcomponentsjs#browser-support :

> The polyfills are intended to work in the latest versions of evergreen browsers. See below for our complete browser support matrix.

At the moment of writing, we thus support Edge 17. We also test on 16 for the time-being, but in general it is latest 2. Therefore, I am closing this issue.
