### ISSUE TITLE
caveats

### ISSUE THREAD

**Issue by trusktr** [webcomponents/custom-elements#12]
Andrea's polyfill has a [caveat in how Custom Element constructors are defined and used](https://github.com/WebReflection/document-register-element#v1-caveat).

Does this polyfill have the same (or similar) caveat? If so, what are the recommendations for end users?

**Comment by Shijir** [comment]
I am using Typescript. And I had to use the following constructor to make it work.

    constructor() {
        return super();
    }

**Comment by bicknellr** [comment]
I'm confused about what the upgrade for procedurally created elements refers to:

> The current standard cannot possibly be polifilled "1:1" with vanilla JavaScript because procedurally created instances need an upgrade.

As far as I know, the main problem with CE v1 and polyfills is that you can't actually write a definition that doesn't use ES2015 that also works with a native implementation. Specifically, to construct a native custom element, you *must* either write it with class syntax and call `super();` or use `Reflect.construct` and pass `new.target` - both of which are syntax errors in ES5.

Is this demo something like what you were asking about in the original question: http://jsbin.com/tapoqam/1/edit?html,output ?

**Comment by trusktr** [comment]
@bicknellr It means that the instance of your element will go from `instanceof HTMLUnknownElement` to `instanceof YourCustomElement` magically, and your reference to it in the code will be the same reference. This magic happens on the native (C/C++) side of the engine, not really polyfillable.

**Comment by trusktr** [comment]
@bicknellr Your example works fine because (I believe?) the polyfill just detects and uses the native implementation. But if you add transpiling (es6+ -> es5) then you run into the issues having to ironically use `Reflect.construct`, etc, even though it isn't es5, because it needs to work when the polyfill detects the native implementation. Transpilation should work fine in a 100% es5 poyfill I think (just guessing, haven't tried yet).

**Comment by azakus** [comment]
README has some caveats for classes with es5 transpilation, this likely should have been closed when that was added.
