### ISSUE TITLE
Can I create new items from HTML string?

### ISSUE THREAD

**Issue by dartess** [webcomponents/custom-elements#124]
I'm sorry, I could not find a solution to this problem.
```
document.body.insertAdjacentHTML('beforeend', '<hello-world who="from console"></hello-world>')
```
it works in chrome, but does not work with polyfill.

Same with innerHTML.

Can this work with this polyfill?

upd: this work in WebReflection's version (`document-register-element`)

**Comment by bicknellr** [comment]
`Element.prototype.insertAdjacentHTML` doesn't have a wrapper to trigger the callbacks yet but [`innerHTML` does](https://github.com/webcomponents/custom-elements/blob/6ad9993949a4f25c05b50b27a031a2ebfc49df89/src/Patch/Element.js#L28). Do you have a repro of setting `innerHTML` that isn't working?

**Comment by dartess** [comment]
I apologize, apparently, I tried the old version.
