### ISSUE TITLE
What if `customElements` exists polyfilled when trying to use the native-shim?

### ISSUE THREAD

**Issue by trusktr** [webcomponents/custom-elements#132]
https://github.com/webcomponents/custom-elements/blob/6ad9993949a4f25c05b50b27a031a2ebfc49df89/src/native-shim.js#L65

What if during that check, `customElements` is already defined by the CE polyfill? Do we have to ensure that native-shim runs before any CE polyfill?

(I'm thinking about how to make this work in a single-file build that runs in old and new browsers, ref: https://github.com/webcomponents/webcomponentsjs/issues/874)

**Comment by bicknellr** [comment]
> Do we have to ensure that native-shim runs before any CE polyfill?

Yes, you have to run the shim before the polyfill and you can't force the polyfill if you're using the shim.

**Comment by bicknellr** [comment]
They don't work together and the polyfill will make the native shim think that custom elements are implemented natively.

**Comment by trusktr** [comment]
Well, it turns out, I don't need to use native-shim at all because [babel-plugin-transform-builtin-classes](https://github.com/WebReflection/babel-plugin-transform-builtin-classes) solves the problem at build time and it works in old and new browsers.

And, what's even better, Babel core adopted these ideas from @WebReflection in https://github.com/babel/babel/pull/7020, so native-shim may soon be a thing of the past!

**Comment by bicknellr** [comment]
> so native-shim may soon be a thing of the past!

Cool, that would be really useful!
