### ISSUE TITLE
npm registry name is incompatible with scoped registries

### ISSUE THREAD

**Issue by justin-hackin** [webcomponents/custom-elements#136]
@ symbol denotes that the package name following it is in a scoped registry.  Therefore, I had to remove my registry= line of my .npmrc file in order to make the package install.  Otherwise, npm installing the package results in 

```
npm ERR! 404 Not Found: @webcomponents/custom-elements
npm ERR! 404 
npm ERR! 404  '@webcomponents/custom-elements' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

**Comment by TimvdLippe** [comment]
This seems to be an NPM-specific issue. If you keep experiencing issues installing this package, please open an issue at https://github.com/npm/npm
