### ISSUE TITLE
Node.append() should be monkeypatched by custom-elements/src/Patch/Node.js

### ISSUE THREAD

**Issue by msujaws** [webcomponents/custom-elements#139]
connectedCallback() is called for Node.appendChild() but not for calls to Node.append().

https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append

**Comment by bicknellr** [comment]
It should be patched already: https://github.com/webcomponents/custom-elements/blob/566a4256d9b45d1f642702aa298e468380b9b1a8/src/Patch/Interface/ParentNode.js#L74
If you're finding that `connectedCallback` isn't called after inserting something with `append`, could you provide a repro?

**Comment by TimvdLippe** [comment]
Closing per above comment. Feel free to reopen this issue if you have a reproduction case.
