### ISSUE TITLE
Native ES6 classes do not work when the native-shim is in use.

### ISSUE THREAD

**Issue by RebeccaStevens** [webcomponents/custom-elements#142]
Currently if the native shim is in use, only es5 custom elements can be used.

**Console Output:**
`Uncaught TypeError: Class constructor MyElement cannot be invoked without 'new'`

**Comment by grimly** [comment]
I already have some ideas on how to fix it, we can use their original idea of a overridden `HTMLElement` but with a super class that supports both types of subclasses. 

The Reflect API can let us work around to perform the super call we want. We can use `eval` to use `new.target` if available and `this.constructor` as a best effort replacement. 

Given the super class would be compatible with every kind of subclasses, we don't need to change the custom elements registry anymore. 

My firm network does not grant me access to push a fix but I will try to make one when I get home.

**Comment by MatteoWebDesigner** [comment]
Hi I notice you changed the arrow function to a normal function. 
That change would make uglifyJS works. When are you going to release it.
I had to copy and manually change the arrow function because I could not Uglify the file.

**Comment by RebeccaStevens** [comment]
@MatteoWebDesigner With the current implementation of the native-shim file, you should not need to uglify it. The current implementation is only supposed to run in browsers with es6 support. The file intentionally uses arrow functions to prevent it running in browsers that only support JS up to es5.

@grimly's pull request switches out arrow functions with with "normal" functions because the file is now designed to run on both es5 and es6 supported browsers.

If you wish to use UglifyJS with es6 support, you need to use [uglify-es](https://www.npmjs.com/package/uglify-es) as documented here: https://github.com/mishoo/UglifyJS2#note

**Comment by MatteoWebDesigner** [comment]
thank you @RebeccaStevens Yes I misunderstood the problem. Yes I am looking to use uglify-es the problem I am using webpack.

**Comment by kirill-konshin** [comment]
At least provide a way to revert everything back.

**Comment by kirill-konshin** [comment]
Awesome! When this is going to be released?

**Comment by bicknellr** [comment]
Just released it as v1.2.0.
