### ISSUE TITLE
Duplicate declaration exception differs from original

### ISSUE THREAD

**Issue by TimvdLippe** [webcomponents/custom-elements#155]
_From @nazar-pc on December 16, 2014 6:44_

Example: http://jsfiddle.net/hoxrjzgk/
Chromium 39 (Native):

> Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'test-element'. A type with that name is already registered.

Firefox Nightly 37 (Polyfill):

> Error: DuplicateDefinitionError: a type with name 'test-element' is already registered

_Copied from original issue: webcomponents/webcomponentsjs#127_

**Comment by bicknellr** [comment]
I think we can safely drop this one since it applies to the v0 polyfill; thanks for pulling it over though.
