### ISSUE TITLE
connectedCallback not invoked if constructor calls attachShadow

### ISSUE THREAD

**Issue by JanMiksovsky** [webcomponents/custom-elements#17]
See http://jsbin.com/tetika/3/edit?html,console,output.

In Canary and STP (with CE turned on), the `connectedCallback` is invoked as expected.
In production Chrome, Firefox, Safari, the `connectedCallback` is not invoked.

This is using the current webcomponents-lite.js from the v1 branch of webcomponents/webcomponentsjs.

**Comment by kevinpschaaf** [comment]
The root cause is a shady DOM bug, see https://github.com/Polymer/polymer/issues/4087

**Comment by bicknellr** [comment]
@JanMiksovsky, this seems to be fixed, do you think we can close?

**Comment by JanMiksovsky** [comment]
@bicknellr Yes, it looks like this has been fixed. Thanks for checking.

**Comment by bicknellr** [comment]
Cool, closing.
