### ISSUE TITLE
Can this polyfill be considered dead?

### ISSUE THREAD

**Issue by def0x099** [webcomponents/custom-elements#186]
Over the least two years, there's been a severe drop in the contributions to this repository, when this polyfill has still not been implemented correctly according to the specification. It is still quite a slow polyfill to run.

Is this because this product is created by **Google**, or a genuine loss of interest?

**Comment by TimvdLippe** [comment]
This polyfill is not dead. We did reach a point where the specification is almost fully implemented. Some parts that we are lacking are either impossible or would result in significant performance degradations. In other words: we don't aim to be 100% correct, but as close to 100% as feasible.

> It is still quite a slow polyfill to run.

Could you provide an example of where our polyfill is slow? Our intention is to write a performant polyfill, so we want to resolve performance issues.

**Comment by azakus** [comment]
Tim's statement is correct. The polyfill is very close to feature complete, and the many of the remaining issues are either difficult to solve, or need extensive evaluation for performance.

Not sure what part of the polyfill you consider slow, but if you have a good reproduction, please file an issue in the monorepo: https://github.com/webcomponents/polyfills/issues
