### ISSUE TITLE
A browser extension overwrites HTMLElement.prototype.appendChild

### ISSUE THREAD

**Issue by steelraiden** [webcomponents/custom-elements#188]
Hi, I just found that some customer of mine, use the extension "http://popup-blocker.org/" for chrome, that overwrites HTMLElement.prototype.appendChild. So, when "setPropertyUnchecked(Node.prototype, 'appendChild'" kicks in, it changes just the Node behaviour, leaving the extension's HTMLElement. 

I fixed simply putting HTMLElement.prototype.appendChild = Node.prototype.appendChild somewhere in my code
Is there a better fix/workaround for this?

**Comment by TimvdLippe** [comment]
The polyfill assumes the native methods are properly implemented. In this case, the extension incorrectly overrides a native method. We can't work around that. You will need to ask the extension author to correct their implementation to be spec-compliant.
