### ISSUE TITLE
CustomElements.js vs @webcomponents/custom-elements/custom-elements.min.js

### ISSUE THREAD

**Issue by Shijir** [webcomponents/custom-elements#21]
Is the CustomElements.js similar to @webcomponents/custom-elements/custom-elements.min.js ? What is the difference? @webcomponents/custom-elements/custom-elements.min.js was working, but the CustomElements.js in this directory not working.

**Comment by noopole** [comment]
CustomElements.js from where?

**Comment by Shijir** [comment]
oh sorry. My question was what is different in this custom-elements.js from CustomElement.js in https://github.com/WebComponents/webcomponentsjs? I know this directory is moved from there. But I would like to know the difference and reasoning behind it. Thanks!

**Comment by noopole** [comment]
Not sure but I think they created a new separate project for the Custom Element polyfill for the needs of the "version 1".

You should use the old one any more, it is not supported any more.

**Comment by SerkanSipahi** [comment]
see this, very useful explanation of customElements v1: https://developers.google.com/web/fundamentals/getting-started/primers/customelements
see also new spec: https://www.w3.org/TR/custom-elements/

**Comment by ebidel** [comment]
Correct. https://github.com/webcomponents/custom-elements is for the v1 CE polyfill. We broke up each polyfill into a separate repo.

https://github.com/WebComponents/webcomponentsjs is v0 APIs.
