### ISSUE TITLE
Consider including the `native-shim` with the polyfill

### ISSUE THREAD

**Issue by sorvell** [webcomponents/custom-elements#25]
This would remove the need for users to decide which part of the polyfill they need to load. The polyfill (which is very small) could simply always be loaded regardless of whether the browser supports custom-elements or not and the code is ES5 or ES6. The `native-shim` should probably continue to be available standalone for users that want the smallest possible code download to a given client.

In this case the `HTMLElement` global would likely always need to be patched. Additionally, it might be necessary to turn on native shimming globally when any ES5 class is defined.

**Comment by treshugart** [comment]
Definitely interested in this. I'm currently trying to find ways to build an `eval()` around it so it only executes in native browsers. Not proud of it, but currently it seems the only way. Once I get that working, I might try and dig a little deeper on this one.

**Comment by treshugart** [comment]
So, I've tentatively landed on [this method](https://github.com/skatejs/web-components/pull/28/files#diff-11e9f7f953edc64ba14b0cc350ae7b9dR11.) which basically only evals() the ES2015 shim if custom elements are supported. Open to better ways, for sure :)

**Comment by clubajax** [comment]
I'm not a fan of this idea, as I think the shims should be kept as small and as specific as possible. Perhaps a different, detection-based-loader shim would work though.
