### ISSUE TITLE
Make connected/disconnected synchronous to match spec

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/custom-elements#34]
Currently the polyfill uses global (and in the case of Shadow DOM, local per root) MutationObservers to detect connection and disconnection of custom elements.  This results in async `connectedCallback` and `disconnectedCallback`, whereas native implementations run these callbacks at "nanotask" timing, synchronous to the DOM mutation method that added/removed the node.  The differences in timing between native and polyfill are often sources of confusion and complexity.

It should be possible to match the spec timing by globally patching the methods that can add/remove nodes from the main document and doing the walks to run `connectedCallback`/`disconnectedCallback`s synchronous to those methods:
* `appendChild`
* `insertBefore`
* `removeChild`
* `remove`
* `replaceChild`
* `innerHTML` _accessor_

This is theoretically no worse in performance than the MO since the exact same treewalk must be done in either case.

The main "hard problem" with this approach is that `innerHTML` is an _accessor_ that can result in added/removed nodes, and some older browsers make this difficult:
* some browsers do not implement the `innerHTML` accessor on the `HTMLElement.prototype`, but rather incorrectly place these accessors on instances, hence it's not as simple as patching `HTMLElement.prototype.innerHTML`, and 
* even when you patch instances (which is theoretically possible without much extra code since the CE polyfill takes a look at every node ever created, albeit at some cost), the property descriptor for the native `innerHTML` accessor does not provide access to the underlying `set`/`get` accessor methods, so once patched to implement scanning for custom elements to connect/disconnect, "tricks" must be used to actually do the normal `innerHTML` work.

**Comment by sorvell** [comment]
Here's one example of an ordering complexity this difference in timing introduces:

A host element creates a `shadowRoot` in its `connectedCallback` and inserts a child custom element inside of it using `appendChild`. Under native custom elements the child's `connectedCallback` is processed before the call to `appendChild` returns. The host element **can depend** on its child element having been connected. Under the polyfill, the child's `connectedCallback` is called asynchronously, and therefore the host **cannot depend** on the child's `connectedCallback` being called.

**Comment by kevinpschaaf** [comment]
To address the `innerHTML` problem, one approach would be to:
1. `Object.defineProperty(node, 'innerHTML', { /* patched getter/setter */ }` on every node during the normal treewalks the polyfill does looking for custom elements
1. Implement the `innerHTML` setter using `innerHTML` on a `div` from a different document (e.g. from an iframe)
1. Implement the `innerHTML` getter by walking the nodes and constructing the inner HTML string manually (implementations of this exist and are fairly straightforward: https://github.com/webcomponents/shadydom/blob/master/src/innerHTML.js#L116)

**Comment by treshugart** [comment]
If you want to support Safari 9 doing accessors is hard because you can't access the native ones (you can in Safari 10). You have to use a DOM parser, but even then there's some quirks to it. For example, in our shadow dom v1 polyfill (no longer supported) we had to do [this](https://github.com/skatejs/named-slots/blob/master/src/v1/index.js#L68) for WebKit.

**Comment by bicknellr** [comment]
@kevinpschaaf, closable?

**Comment by kevinpschaaf** [comment]
Yes!  Resolved via https://github.com/webcomponents/custom-elements/pull/43
