### ISSUE TITLE
Improve performance relative to native implementation

### ISSUE THREAD

**Issue by sorvell** [webcomponents/custom-elements#38]
The current polyfill uses lots of MutationObservers try to catch all of the dom manipulations that could cause an element to need to customize. Unfortunately, this results in a significant amount of overhead and hinders performance.

Here's a quick perf check demo:

native (Chrome only): http://output.jsbin.com/bejawep
polyfill: http://output.jsbin.com/teveman
polyfill modified to not use as many MutationObservers: http://output.jsbin.com/xacefo
other polyfill for comparison: http://output.jsbin.com/tewesi

**Comment by bicknellr** [comment]
@sorvell, closable?

**Comment by dalvarezmartinez1** [comment]
We're having similar problems for big datasets, **loading a datatable with ~7000 rows and 4 columns takes about 5min with the custom-elements polyfill (IE11)**, and around 5 seconds without (Chrome67).

After looking at the performance tab I discovered that most of the time (~99%) is spent adding or removing children (depending on the usecase: initial load or reload), the 3rd column (98.36%) is percentage of the whole time of those 5 minutes.
![image](https://user-images.githubusercontent.com/4959873/47366943-f7023180-d6de-11e8-835a-08ab72ae764b.png)

I would attach the .diagsession which can be loaded into Edge, but it's ~ 80MB which is bigger than the 10MB limit.

**Comment by azakus** [comment]
Not sure if you still need help with this @dalvarezmartinez1, but you should use https://github.com/webcomponents/polyfills/tree/master/packages/custom-elements#customelementspolyfillwrapflushcallback
