### ISSUE TITLE
HTML Imports as its own shim 

### ISSUE THREAD

**Issue by clubajax** [webcomponents/custom-elements#39]
I'd like to see the shim be kept as small as possible, and believe it would be beneficial for the HTML Imports to be their own shim. This also seems to be a valid path seeing as Imports are one of the specs that is still under contention.

For my use case, I plan to not use Imports and instead use (SystemJS) ES modules, and template strings.

**Comment by TimvdLippe** [comment]
The HTML imports polyfill has been extracted to https://github.com/webcomponents/html-imports
