### ISSUE TITLE
`attributeChangedCallback` is called twice when the attribute is changed

### ISSUE THREAD

**Issue by linsolas** [webcomponents/custom-elements#44]
Hello,

On the `custom-element` polyfill, the function `attributeChangedCallback` is called twice when an attribute, listed in the `observedAttributes()`, is changed.

```html
<my-component id="compo" foo="bar"></my-component>
<button id="myBtn">Change value</button>
```

```js
class MyComponent extends HTMLElement {
  constructor() {
    super();
  }
  
  static get observedAttributes() { return ['foo']; }
  
  attributeChangedCallback(attrName, oldVal, newVal) {
    console.log('[my component] attribute', attrName, 'changed from', oldVal, 'to', newVal);
  }
}

window.customElements.define('my-component', MyComponent);
```

The logs are as follows:

```
[my component] attribute foo changed from null to bar
click on the button to change the attribute value
[my component] attribute foo changed from bar to baz
[my component] attribute foo changed from bar to baz
```

As you can see, the line `[my component] attribute foo changed from bar to baz` is called twice.

Here is a JsFiddle to test that example: https://jsfiddle.net/czo1355c/

The issue is encountered on a Chrome v53, since starting with v54, `customElements` is natively supported by Chrome (and the function `attributeChangedCallback` is only called once).
Tested against version `1.0.0-alpha.3` of custom-element library.

Thanks

**Comment by chiefcll** [comment]
It looks like the patching of setAttribute is causing this...

https://github.com/webcomponents/custom-elements/blob/master/src/custom-elements.js#L759-L766

The _handleAttributeChange is calling the callback, and if you use setAttribute that will also call it, leading to it being called twice.

**Comment by bicknellr** [comment]
This should be fixed: http://jsbin.com/vefilax/edit?html,console,output
