### ISSUE TITLE
Documentation needs correction on IE10 support

### ISSUE THREAD

**Issue by Shijir** [webcomponents/custom-elements#47]
In the `src/README.md`, it says:

```
The implementation should work without additional polyfills in IE 11, Edge, Safari >6, Firefox, Chrome, Android Browser >4.4, and Opera (not Mini).

IE 10 should be supported with the Mutation Observer polyfill.
```

However, IE10 support not only requires Mutation Observer polyfill, but also polyfills for new ES2015 globals such as `Map` as the current build doesn't polyfill `Map`. Thus, in order to make the polyfill work in IE10, users also need to load [core-js](https://github.com/zloirock/core-js) or other similar libraries.

**Comment by bicknellr** [comment]
Shortly after filing this bug, `src/README.md` was removed and the root `README.md`, which was mostly rewritten, should be the only README now. It doesn't mention anything about browser support even though it probably should, but [the browsers listed in the webcomponentsjs repo](https://github.com/webcomponents/webcomponentsjs#browser-support) are the official set. I think that should be sufficient to close this particular issue but, if you think this needs clarification / a link in the local README, feel free to send a PR.
