### ISSUE TITLE
Custom Element v1 error on chrome

### ISSUE THREAD

**Issue by notwaldorf** [webcomponents/custom-elements#50]
_From @warnerandy on August 3, 2016 18:32_

I am seeing this error on occasion at page load. I'm only using the custom elements v1 polyfill in this scenario.

<img width="841" alt="screen shot 2016-08-03 at 12 30 41 pm" src="https://cloud.githubusercontent.com/assets/44771/17377260/314f1c56-5976-11e6-9af8-7e0136858724.png">

_Copied from original issue: webcomponents/webcomponentsjs#586_

**Comment by bicknellr** [comment]
The error message in your screenshot makes it pretty clear that this was something specific to the polyfill from before v1.0.0-alpha.4 . I'd say update and give it another try under the same conditions, then post something here if you're still running into this.
