### ISSUE TITLE
native-shim HTMLElement prototype is the old function?

### ISSUE THREAD

**Issue by notwaldorf** [webcomponents/custom-elements#51]
_From @trusktr on June 1, 2016 8:27_

I see the line

``` js
  HTMLElement.prototype = Object.create(origHTMLElement);
```

But should it be

``` js
  HTMLElement.prototype = Object.create(origHTMLElement.prototype);
```

? If the prototype is the `origHTMLElement`, that would mean that the `origHTMLElement.*` static properties will be HTMLElement instance properties?

_Copied from original issue: webcomponents/webcomponentsjs#546_

**Comment by notwaldorf** [comment]
_From @justinfagnani on August 30, 2016 7:43_

I think I just fixed this, though I admittedly don't have tests for the shim.

**Comment by bicknellr** [comment]
This should be fixed: [here's where we get HTMLElement](https://github.com/webcomponents/custom-elements/blob/8fd028c456dbfbc88cf325ad18bd2f37d6e6dd1a/src/Patch/Native.js#L28) and [here's where we assign it's prototype as the prototype of the replacement HTMLElement constructor](https://github.com/webcomponents/custom-elements/blob/8fd028c456dbfbc88cf325ad18bd2f37d6e6dd1a/src/Patch/HTMLElement.js#L50).
