### ISSUE TITLE
Can not call super?

### ISSUE THREAD

**Issue by Nitin-Prabhakar** [webcomponents/custom-elements#6]
I defined a class for a custom div element like so:
```js
class myAwesomeDiv extends HTMLDivElement{

  constructor(){
    super();
    this.addEventListener('click',e=>this.toggleFav());
  }
 toggleFav(){}
}
```
and on using it as `<awesome-div></awesome-div>` , 

I am seeing this (line 82 in app.js is the call to `super()`)
![screenshot from 2016-09-09 21-05-29](https://cloud.githubusercontent.com/assets/15086525/18392974/6b4974b0-76d1-11e6-9e8a-58fad94d80b3.png)

**Comment by justinfagnani** [comment]
You can't extend `HTMLDivElement` right now. We'll be adding customized built-in elements support soon.

**Comment by Nitin-Prabhakar** [comment]
thanks @justinfagnani . Is there a list of elements currently supported?

**Comment by justinfagnani** [comment]
Only `HTMLElement`

**Comment by TypedSource** [comment]
are you still working on it?

i need self defined input and textarea elements in forms ;)

**Comment by justinfagnani** [comment]
We're still in a situation where we have no native implementations of customized built in elements. That may change soon...

**Comment by peacememories** [comment]
It seems like Chrome supports it as far as I can tell. I would love to have access to this feature via a polyfill so I can extend the functionality of a textarea.
