### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by chiefcll** [webcomponents/custom-elements#61]
Its been a while and lots of changes occurring - do you have an RC that we can start using?

**Comment by bicknellr** [comment]
I tagged v1.0.0-alpha.4 earlier today but I'd have to ask around if we would want to call this a release candidate. FWIW, we're currently referencing the master branch here from [webcomponentsjs#v1](https://github.com/webcomponents/webcomponentsjs/blob/v1/bower.json), which brings together our updates for the v0 -> v1 spec changes. I think the intent is to tag everything across the polyfill repos all at once.

**Comment by bicknellr** [comment]
(Closing because there's a new tag to reference. If there's something preferable to this you had in mind, let me know.)
