### ISSUE TITLE
FireFox 51 (curet) fails Custom Elements: `Element#attachShadow` was not patched.

### ISSUE THREAD

**Issue by puppetmaster3** [webcomponents/custom-elements#63]
I get Custom Elements: `Element#attachShadow` was not patched error.

Works fine on Chrome.
https://www.masons-foundation.org/home/feed/

FireFox 51 and poly v 1.04a - both latest.

**Comment by puppetmaster3** [comment]
More info:
- the component code is here, so you don't have to view code: view-source:https://www.masons-foundation.org/_compHost/home-card.html

- safari works.

- firefox dev preview v53 has same error

- firefox does work on a different page https://amp.masons-foundation.org/post/asites/

But https://www.masons-foundation.org/home/feed/ in FF makes error:
Custom Elements: Element#attachShadow was not patched.

**Comment by bicknellr** [comment]
Oh, this is just telling you that `Element#attachShadow` doesn't exist (you're running in a situation without Shadow DOM) and that it didn't patch the (non-existent) function. Maybe I should have used `console.info` instead of `console.warn` for these. You shouldn't need to worry about this if you aren't using Shadow DOM.

**Comment by bicknellr** [comment]
If you're using a Shadow DOM polyfill and you're still seeing this error, you need to load the Shadow DOM polyfill first so that it can do its patching before the custom elements polyfill does its own.

**Comment by bicknellr** [comment]
@puppetmaster3, I'm going to close this since I don't think this is actually a bug. If you find that this still happens in situations where you're using Shadow DOM, please leave a comment and I'll reopen it.
