### ISSUE TITLE
trouble with native-shim and camelCase svg attributes

### ISSUE THREAD

**Issue by micahscopes** [webcomponents/custom-elements#66]
SVG elements have attributes like "viewBox", but native-shim's setAttribute is lowercasing all attribute names.  It's interfering with my ability to use SVG elements!

**Comment by micahscopes** [comment]
I was using skatejs/web-components, which depends on an older version of native-shim.  I'll fix it there.

**Comment by aaronshaf** [comment]
I am still having an issue with this. It's strange: If I have the polyfill anywhere on the page, SVGs created by React have lower-case `viewbox`

**Comment by micahscopes** [comment]
@aaronshaf that's very strange, maybe post some details here: 
 https://github.com/webcomponents/custom-elements/issues/14
