### ISSUE TITLE
TypeError: fakeClass is not a constructor

### ISSUE THREAD

**Issue by clubajax** [webcomponents/custom-elements#67]
I'm getting this error while attempting to do a simple custom-element using webpack.

My setup:
```
<script src="/custom-elements.min.js"></script>
<script src="/native-shim.js"></script>
export default class TodoApp extends HTMLElement {
	constructor () {
		super();
		console.log('CONSTRUCT');
	}
}
```

The error happens on line 98 of native-shim:

```
window.HTMLElement = function() {
    if (!browserConstruction) {
      const tagname = tagnameByConstructor.get(this.constructor);
      const fakeClass = nativeGet.call(window.customElements, tagname);

      // Make sure that the fake constructor doesn't call back to this constructor
      userConstruction = true;
      const instance = new (fakeClass)();
      return instance;
    }
    // Else do nothing. This will be reached by ES5-style classes doing
    // HTMLElement.call() during initialization
    browserConstruction = false;
  };
```

"tagname" is undefined.

I've tried different version of babel, including "latest". I've tried changing the order of the shims and excluding the native shim.

**Comment by treshugart** [comment]
I've gotten this error when I would forget to register the custom element
via customElements.define(). I don't see your code doing that?

**Comment by clubajax** [comment]
I don't know how to recreate this error - I must have had a bad setup somehow. This can be closed.

**Comment by bicknellr** [comment]
Possibly related to https://github.com/webcomponents/webcomponentsjs/issues/750?
