### ISSUE TITLE
Release alpha 4 to NPM

### ISSUE THREAD

**Issue by alexlafroscia** [webcomponents/custom-elements#68]
I'm working on getting the custom elements polyfill included into Polyfill.io, and noticed that the latest release that's available on NPM is alpha 3, despite alpha 4 being tagged on Github. Is there a reason the latest isn't on NPM yet? If not, would you mind pushing the update to there as well? I'd rather not link to Github for the dependency if I can avoid it.

**Comment by aaronshaf** [comment]
Please release this :)

**Comment by jaffoneh** [comment]
Do we have an update on this? We would like to be able to use it for: https://github.com/vmware/clarity/issues/546 as well. Thanks!

**Comment by alexlafroscia** [comment]
At this point I doubt alpha 4 will be released on NPM since it seems like there have been two release candidates since then. Here's hoping the official release comes soon!

**Comment by bicknellr** [comment]
@justinfagnani, do you have access to the webcomponents org on NPM?

**Comment by justinfagnani** [comment]
I must? I think I published the package originally.

**Comment by bicknellr** [comment]
Just published `v1.0.0-rc.3`.
