### ISSUE TITLE
TypeError: Attempting to configurable attribute of unconfigurable property

### ISSUE THREAD

**Issue by robhicks** [webcomponents/custom-elements#70]
This is for v1.0.0-rc.1 and also v1.0.0-alpha.4. 

When running tests with PhantomJS 2.1.14, this error is thrown:

```shell
TypeError: Attempting to configurable attribute of unconfigurable property.
  at dist/components/idx-nwc/dist/webcomponents/custom-elements.min.js:18
```

Error first appeared in v1.0.0-alpha.4.

**Comment by cronon** [comment]
The error is thrown when the polyfill tries to patch nodes with `Object.defineProperty`. Phantomjs has dozen of related issues. https://github.com/ariya/phantomjs/issues/13895
There was a dirty workaround to use `__defineGetter__` method, nevertheless I tried and it didn't work

**Comment by Mirodil** [comment]
The same issue

**Comment by rootical** [comment]
Subscribing, blocks quite a lot of work on this end.

**Comment by treshugart** [comment]
I'm not sure this is fixable due to the PhantomJS unconfigurable issues and the fact that it's [been deprecated in favour of Chrome headless](https://groups.google.com/forum/m/#!topic/phantomjs/9aI5d-LDuNE).

**Comment by TimvdLippe** [comment]
Sadly this is an issue in PhantomJS and it is deprecated. Therefore I am closing this issue.
