### ISSUE TITLE
Polyfill doesn't work if another script patches the DOM

### ISSUE THREAD

**Issue by joeldenning** [webcomponents/custom-elements#72]
In the following case, the polyfill does not work because the functions it patches on the DOM (such as `document.createElement`) are never actually called:

```html
<html>
  <body>
    <script>
      var originalCreateElement = document.createElement;
      document.createElement = function() {
        console.log("Someone else doing something by patching the DOM");
        return originalCreateElement.apply(this, arguments);
      }

      customElements.forcePolyfill = true;
    </script>
    <script src="https://raw.githubusercontent.com/webcomponents/custom-elements/master/custom-elements.min.js"></script>
  </body>
</html>
```

I discovered this because I have the LastPass chrome extension, which patches `document.createElement` as above. The reason why there is a bug is because [the CE polyfill patches `Document.prototype`](https://github.com/webcomponents/custom-elements/blob/master/src/Patch/Document.js#L11) instead of patching `document.createElement` directly. In the example above, `originalCreateElement` is a reference to the native `createElement`, so when `originalCreateElement.apply(this, arguments)` is called, it calls the native implementation without calling the patched version that CE polyfill puts onto Document.prototype.

Another way of wording this is that patching `Document.prototype` assumes that `document` will actually use its prototype's implementation of `createElement`, instead of `document` having its own property called `createElement`.

I see this as a pretty crucial bug to fix, since patching createElement with `document.createElement = ` is a common practice. I'm still thinking about what the full fix for this is, though. If we change the polyfill code to also patch `document.createElement = ` directly, then that may leave out other `Document` instances. But if you don't patch it that way, then you're in trouble if anybody else on the page is doing so.

**Comment by bicknellr** [comment]
I don't think this is a bug in the polyfill or something that it should attempt to work around. IMHO, LastPass should fix their extension to get the function from the right place and put their replacement in that same place (`Document.prototype`).

**Comment by joeldenning** [comment]
patching functions directly on `document` is something that I have seen in several codebases (not just LastPass), which has me worried. What are the reasons you prefer patching `Document.prototype`? Are you worried about other instances of `Document` besides `document`? Or is it more just that `Document.prototype` is the *right* place to do it?

My thoughts are that a polyfill really can't expect a browser environment to be especially cooperative, and that the code should be defensive so that it works in as many situations as possible. What do you think?

**Comment by snuggs** [comment]
It's both @joeldenning.The `Document.prototype` is the appropriate place to do this. Regardless if the alternative is commonplace. Also there is the notion of `Document` potentially being multiple. From `DocumentFragment` to `<iframe>` to HTML Imports, (Even HTML module imports) best to use the Web API ` Document` for enhancements instead of reaching into `window.document` for monkey patching. Which has been a smelly side effect (pun intended) since Javascript's inception. Also not safe to assume `document` is what you expect it to be moving forward now that we have a Global Environment Record that is separate from `window` however has same global variable access as `window`. This is where `const` `let` `class` memory space are held. 

/cc @bicknellr

**Comment by bicknellr** [comment]
I had to install the extension and dig around in it to figure out where they did their patch. AFAIK, there's no real source available. :/

**Comment by TimvdLippe** [comment]
Closing this as a wont-fix. The polyfill is intended to implement the steps as stated in the specification. If users overwrite functions like these, not only this polyfill breaks but also other scripts can break.

**Comment by usergenic** [comment]
This is my relatively simple workaround/fix https://gist.github.com/usergenic/9baf88a24dcbc77bc808339755a7d436
