### ISSUE TITLE
[Windows] Cannot build with gulp

### ISSUE THREAD

**Issue by rubenhazelaar** [webcomponents/custom-elements#8]
Unfortunatly I cannot build the minified files. To install I did the following: 

```
git clone https://github.com/webcomponents/custom-elements
cd custom-elements
npm i
```

(Instructions in the README.md are not updated yet I believe)

To build:

```
gulp
[18:19:30] Using gulpfile ~\code\custom-elements\gulpfile.js
[18:19:30] Starting 'default'...
```

However my tty returns to me without a "Finished" message. No directory is created and of course also no minified files.

**Comment by justinfagnani** [comment]
Since gulp sometimes likes to swallow errors, can you make sure you have Java installed? I'll test in my Windows VM asap.

**Comment by rubenhazelaar** [comment]
Yes Java is installed (8.0.910.15) on Win 10. It seems to be a problem with the closure compiler.

**Comment by jarek-foksa** [comment]
Could you please just provide the pre-built `custom-elements.min.js` file rather than requiring everyone to compile from source?

**Comment by Meai1** [comment]
Hi, where is the non minified file? The sourcemaps are a pain to work with, they dont let me print out variables via their original names so it's really mostly useless.
